---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: voting-db-credentials
  namespace: web-apps
spec:
  encryptedData:
    db-password: AgCVA922ffT4nljqXYttWgWCqV71UVRz3cgMaWv2IipjN5lxsmFfX6hCWOyJPxOJltI6qY4q573JdPOzksmZQZaXH/bNxq8NJE2qb9UelaBnn/pdogtglpwPd7DVXMAlJFKDg45wZJ59IK4fy5XUOf3RMu1iVSiIdD7o4+09jmJ7XeU6Me1lTsrKlI+n/SGU03mb4BQJrmISvJydg6JJsLU4n6SRccoQD9imBRUBmHnWJMfE7B1kJ6fzHN4+YNO3OXkcFSoiBQ2zmaZ1q16pdAD7EApgxkowWJmA7o9w8A1FtU4fgs7pbC4jgZkBoKHI4zMfylwEiMZ3Ox/haAKpFAmD4lQhcYErnyIZccWJArED/tM89UTMrTuoJVWcD90yc0ZWyq0POLukGTpPVXBZT1Vyj2ngoRRqgybxV0GPRIS1qxdhPryeoFQJMLH4JFDrNOuqI5sVF6SpRD8XhCNpxSOTEjrgnii8Bt7nqiWFrZsgB248YBz30p0V0msBrRfxL27oWQT4U2rpzzDXjopsPyzLpUE3pSQDbwuHwDjo+I0LYRmytgB4k4XZSehZJSaduCW1UAAip7ySkiQ5eDhNRzQBF4rI1+jo6PEeNCHN6p6oGIgNurhHoM9f8k1n8QevFUtdtUeXYjEn94aYByXDPy6Xfg7UchghtTwurvNWcB7Kprw+o+xFehJV0AgLZdwsfIUSoeXzXVxRUAAzP8Q2lyt7zhSYtZGgJKoEh+uTWlP3lXI=
  template:
    metadata:
      name: voting-db-credentials
      namespace: web-apps
    type: Opaque
